export const CARDS = [
  { id: '1', leftConcept: 'Sıcak', rightConcept: 'Soğuk' },
  { id: '2', leftConcept: 'Kötü Film', rightConcept: 'İyi Film' },
  { id: '3', leftConcept: 'Yararsız', rightConcept: 'Yararlı' },
  { id: '4', leftConcept: 'Sıkıcı', rightConcept: 'Eğlenceli' },
  { id: '5', leftConcept: 'Ucuz', rightConcept: 'Pahalı' },
  { id: '6', leftConcept: 'Yumuşak', rightConcept: 'Sert' },
  { id: '7', leftConcept: 'Tehlikeli', rightConcept: 'Güvenli' },
  { id: '8', leftConcept: 'Hafif', rightConcept: 'Ağır' },
  { id: '9', leftConcept: 'Zor', rightConcept: 'Kolay' },
  { id: '10', leftConcept: 'Çirkin', rightConcept: 'Güzel' },
];

export const PLUS_CARDS = [
  { id: 'p1', leftConcept: 'Sevilay değil', rightConcept: 'Sevilay' },
  { id: 'p2', leftConcept: 'Yusuf değil', rightConcept: 'Yusuf' },
  { id: 'p3', leftConcept: 'Efe değil', rightConcept: 'Efe' },
  { id: 'p4', leftConcept: 'Kardi değil', rightConcept: 'Kardi' },
  { id: 'p5', leftConcept: 'Sıla değil', rightConcept: 'Sıla' },
  { id: 'p6', leftConcept: 'Ayşe değil', rightConcept: 'Ayşe' },
  { id: 'p7', leftConcept: 'Ceren değil', rightConcept: 'Ceren' },
  { id: 'p8', leftConcept: 'Normal okul', rightConcept: 'Hürriyet' },
  { id: 'p9', leftConcept: 'Normal kardeş', rightConcept: 'Sevilayın kardeşi' },
  { id: 'p10', leftConcept: 'Nok flört', rightConcept: 'Ok flört' },
  { id: 'p11', leftConcept: 'Red flag', rightConcept: 'Green flag' },
  { id: 'p12', leftConcept: 'Yatakta hayır', rightConcept: 'Yatakta evet' },
  { id: 'p13', leftConcept: 'Masum', rightConcept: 'Sapık' },
  { id: 'p14', leftConcept: 'Seks odaklı', rightConcept: 'Romantik' },
  { id: 'p15', leftConcept: 'Utangaç', rightConcept: 'Girişken' },
  { id: 'p16', leftConcept: 'Fantezi', rightConcept: 'Gerçekçi' },
  { id: 'p17', leftConcept: 'Mesafeli', rightConcept: 'Yapışkan' },
  { id: 'p18', leftConcept: 'Aseksüel çakması', rightConcept: 'Seks delisi' },
  { id: 'p19', leftConcept: 'Çakar', rightConcept: 'Çakarım' },
  { id: 'p20', leftConcept: 'Sevimli', rightConcept: 'İnanılmaz hot' },
  { id: 'p21', leftConcept: 'Str8', rightConcept: 'Gay' },
  { id: 'p22', leftConcept: 'Vanilla', rightConcept: 'Kinky' },
  { id: 'p23', leftConcept: 'Friendzone', rightConcept: 'Evlenecek insan' },
  { id: 'p24', leftConcept: 'Tanışılmaz', rightConcept: 'İlk görüşte aşık olunur' },
  { id: 'p25', leftConcept: 'Güvenilmez', rightConcept: 'Güvenilir' },
  { id: 'p26', leftConcept: 'Ghostlar', rightConcept: 'Asla ghostlamaz' },
  { id: 'p27', leftConcept: 'Ulaşılmaz', rightConcept: 'Fazla müsait' },
  { id: 'p28', leftConcept: 'Azgın teke', rightConcept: 'Tek eş odaklı' },
  { id: 'p29', leftConcept: 'İlişki istemez', rightConcept: 'Evlilik odaklı' },
  { id: 'p30', leftConcept: 'Kaçar', rightConcept: 'Bağlanır' },
  { id: 'p31', leftConcept: 'Toksik', rightConcept: 'Huzurlu' },
  { id: 'p32', leftConcept: 'Dramatik', rightConcept: 'Sakin' },
  { id: 'p33', leftConcept: 'Kıskanç değil', rightConcept: 'Aşırı kıskanç' },
  { id: 'p34', leftConcept: 'Çocuksu', rightConcept: 'Olgun' },
  { id: 'p35', leftConcept: 'Libidosu çok düşük', rightConcept: 'Libidosu çok yüksek' },
  { id: 'p36', leftConcept: 'Yavaş ilerler', rightConcept: 'Hemen aksiyona girer' },
  { id: 'p37', leftConcept: 'Sarılma odaklı', rightConcept: 'Tutku odaklı' },
  { id: 'p38', leftConcept: 'Dominant', rightConcept: 'İtaatkâr' },
  { id: 'p39', leftConcept: 'Kontrol etmeyi sever', rightConcept: 'Kontrol edilmeyi sever' },
  { id: 'p40', leftConcept: 'Fantezi sevmez', rightConcept: 'Fantezi sever' },
  { id: 'p41', leftConcept: 'Güvenli oynar', rightConcept: 'Sınır zorlar' },
  { id: 'p42', leftConcept: 'Sessiz', rightConcept: 'Gürültülü' },
  { id: 'p43', leftConcept: 'Tek gecelik ilişki', rightConcept: 'Uzun ilişki' },
  { id: 'p44', leftConcept: 'Annenle tanıştırılır', rightConcept: 'Sadece bir gece' },
  { id: 'p45', leftConcept: 'Melek', rightConcept: 'Şeytan' },
  { id: 'p46', leftConcept: 'Duygusal', rightConcept: 'Mantıkçı' },
  { id: 'p47', leftConcept: 'Kalp kırar', rightConcept: 'Kalbi kırılır' },
  { id: 'p48', leftConcept: 'Aşık olunası', rightConcept: 'Uzak durulası' },
  { id: 'p49', leftConcept: 'Manipülatif', rightConcept: 'Samimi' },
  { id: 'p50', leftConcept: 'Gizemli', rightConcept: 'Açık kitap' },
  { id: 'p51', leftConcept: 'İlgi bağımlısı', rightConcept: 'İlgiden kaçar' },
  { id: 'p52', leftConcept: 'İltifat alır', rightConcept: 'İltifat eder' },
  { id: 'p53', leftConcept: 'Zor beğenir', rightConcept: 'Herkesten hoşlanır' },
  { id: 'p54', leftConcept: 'Sevgili materyali', rightConcept: 'Hookup materyali' },
  { id: 'p55', leftConcept: 'Korumacı', rightConcept: 'Umursamaz' },
  { id: 'p56', leftConcept: 'Güven verir', rightConcept: 'Güvensizlik verir' },
  { id: 'p57', leftConcept: 'Kıskandırır', rightConcept: 'Kıskanır' },
  { id: 'p58', leftConcept: 'Baskın aura', rightConcept: 'Uysal aura' },
  { id: 'p59', leftConcept: 'Zarif', rightConcept: 'Kaba' },
  { id: 'p60', leftConcept: 'İyi çocuk', rightConcept: 'Baddie' },
  { id: 'p61', leftConcept: 'Evcimen', rightConcept: 'Gece hayatı insanı' },
  { id: 'p62', leftConcept: 'Dokunmaya çekinir', rightConcept: 'Temas bağımlısı' },
  { id: 'p63', leftConcept: 'Düzgün', rightConcept: 'Kaotik' },
  { id: 'p64', leftConcept: 'Filtreli', rightConcept: 'Patavatsız' },
  { id: 'p65', leftConcept: 'Maske takar', rightConcept: 'Olduğu gibi' },
  { id: 'p66', leftConcept: 'Şans verilir', rightConcept: 'Asla şans verilmez' },
  { id: 'p67', leftConcept: 'Anne onaylı', rightConcept: 'Arkadaşlar bile uzak dur der' },
  { id: 'p68', leftConcept: 'Yumuşak', rightConcept: 'Sert' },
  { id: 'p69', leftConcept: 'Uyumlu', rightConcept: 'İnatçı' },
  { id: 'p70', leftConcept: 'Çapkın görünür', rightConcept: 'Masum görünür' },
  { id: 'p71', leftConcept: 'Golden retriever energy', rightConcept: 'Black cat energy' },
  { id: 'p72', leftConcept: 'Evlenir', rightConcept: 'Aldatır' },
  { id: 'p73', leftConcept: 'İdeal partner', rightConcept: 'Walking red flag' },
  { id: 'p74', leftConcept: 'Kalıcı', rightConcept: 'Gececi' },
  { id: 'p75', leftConcept: 'Prens/Prenses', rightConcept: 'Şeytan' },
  { id: 'p76', leftConcept: 'Güvenli seçim', rightConcept: 'Heyecanlı seçim' },
  { id: 'p77', leftConcept: 'Düz', rightConcept: 'Karizmatik' },
  { id: 'p78', leftConcept: 'Aurasız', rightConcept: 'Aura manyağı' },
  { id: 'p79', leftConcept: 'Ezik', rightConcept: 'Alpha' },
  { id: 'p80', leftConcept: 'NPC', rightConcept: 'Main character' },
  { id: 'p81', leftConcept: 'Soft', rightConcept: 'Hard' },
  { id: 'p82', leftConcept: 'Saf', rightConcept: 'Kurnaz' },
  { id: 'p83', leftConcept: 'Dürüst', rightConcept: 'Düzenbaz' },
  { id: 'p84', leftConcept: 'Egoist', rightConcept: 'Özverili' },
  { id: 'p85', leftConcept: 'Mütevazı', rightConcept: 'Kibirli' },
  { id: 'p86', leftConcept: 'Pasif', rightConcept: 'Agresif' },
  { id: 'p87', leftConcept: 'Uysal', rightConcept: 'Baskın' },
  { id: 'p88', leftConcept: 'Planlı', rightConcept: 'Spontane' },
  { id: 'p89', leftConcept: 'Kontrollü', rightConcept: 'Dürtüsel' },
  { id: 'p90', leftConcept: 'Rahat', rightConcept: 'Gergin' },
  { id: 'p91', leftConcept: 'Sabırlı', rightConcept: 'Sabırsız' },
  { id: 'p92', leftConcept: 'Ciddi', rightConcept: 'Şakacı' },
  { id: 'p93', leftConcept: 'Sessiz', rightConcept: 'Konuşkan' },
  { id: 'p94', leftConcept: 'Sıkıcı', rightConcept: 'Eğlenceli' },
  { id: 'p95', leftConcept: 'Normal', rightConcept: 'Tuhaf' },
  { id: 'p96', leftConcept: 'Cool', rightConcept: 'Cringe' },
  { id: 'p97', leftConcept: 'Evcimen', rightConcept: 'Maceracı' },
  { id: 'p98', leftConcept: 'Güvenli', rightConcept: 'Tehlikeli' },
  { id: 'p99', leftConcept: 'Naif', rightConcept: 'Vahşi' },
  { id: 'p100', leftConcept: 'Fedakâr', rightConcept: 'Bencil' },
  { id: 'p101', leftConcept: 'Şefkatli', rightConcept: 'Acımasız' },
  { id: 'p102', leftConcept: 'Bağımsız', rightConcept: 'Muhtaç' },
  { id: 'p103', leftConcept: 'Alçakgönüllü', rightConcept: 'Kendine hayran' },
  { id: 'p104', leftConcept: 'Karizmatik', rightConcept: 'Silik' },
  { id: 'p105', leftConcept: 'İlgi odağı', rightConcept: 'Arka planda' },
  { id: 'p106', leftConcept: 'Dominant aura', rightConcept: 'Tatlı aura' },
  { id: 'p107', leftConcept: 'Sunshine', rightConcept: 'Storm' },
  { id: 'p108', leftConcept: 'Aşık eder', rightConcept: 'Arkadaş kalır' },
  { id: 'p109', leftConcept: 'Kıskanmaz', rightConcept: 'Delicesine kıskanır' },
  { id: 'p110', leftConcept: 'Sahiplenmez', rightConcept: 'Sahiplenir' },
  { id: 'p111', leftConcept: 'İlgi vermez', rightConcept: 'İlgi bağımlısı' },
  { id: 'p112', leftConcept: 'Sevgi göstermez', rightConcept: 'Sevgi bombardımanı' },
  { id: 'p113', leftConcept: 'Düz', rightConcept: 'Baştan çıkarıcı' },
  { id: 'p114', leftConcept: 'Tutkulu', rightConcept: 'Duygusuz' },
  { id: 'p115', leftConcept: 'Yavaş yanar', rightConcept: 'Anında tutuşur' },
  { id: 'p116', leftConcept: 'Göz teması kaçar', rightConcept: 'Gözleriyle soyar' },
  { id: 'p117', leftConcept: 'Masum bakış', rightConcept: 'Kirli bakış' },
  { id: 'p118', leftConcept: 'Bebek yüzlü', rightConcept: 'Femme fatale' },
  { id: 'p119', leftConcept: 'Temiz yüzlü', rightConcept: 'Günahkâr' },
  { id: 'p120', leftConcept: 'Kalp', rightConcept: 'Hormon' },
  { id: 'p121', leftConcept: 'Kelebek etkisi', rightConcept: 'Deprem etkisi' },
  { id: 'p122', leftConcept: 'Kırılgan', rightConcept: 'Dayanıklı' },
  { id: 'p123', leftConcept: 'Hassas', rightConcept: 'Kalın derili' },
  { id: 'p124', leftConcept: 'Empatik', rightConcept: 'Duyarsız' },
  { id: 'p125', leftConcept: 'Vicdanlı', rightConcept: 'Vicdansız' },
  { id: 'p126', leftConcept: 'Affeder', rightConcept: 'Kin tutar' },
  { id: 'p127', leftConcept: 'Güvenir', rightConcept: 'Şüphecidir' },
  { id: 'p128', leftConcept: 'İdealist', rightConcept: 'Çıkarcı' },
  { id: 'p129', leftConcept: 'Romantik hayalperest', rightConcept: 'Gerçekçi' },
  { id: 'p130', leftConcept: 'Pozitif', rightConcept: 'Negatif' },
  { id: 'p131', leftConcept: 'İyimser', rightConcept: 'Karamsar' },
  { id: 'p132', leftConcept: 'Çalışkan', rightConcept: 'Tembel' },
  { id: 'p133', leftConcept: 'Düzenli', rightConcept: 'Dağınık' },
  { id: 'p134', leftConcept: 'Dakik', rightConcept: 'Geç kalır' },
  { id: 'p135', leftConcept: 'Disiplinli', rightConcept: 'Dağınık ruh' },
  { id: 'p136', leftConcept: 'Mükemmeliyetçi', rightConcept: 'Umursamaz' },
  { id: 'p137', leftConcept: 'Kibar', rightConcept: 'Kaba oç' },
  { id: 'p138', leftConcept: 'Nazik', rightConcept: 'Sert mizaçlı' },
  { id: 'p139', leftConcept: 'Centilmen', rightConcept: 'Serseri' },
  { id: 'p140', leftConcept: 'Çapkın görünür', rightConcept: 'Sadık görünür' },
  { id: 'p141', leftConcept: 'İlk izlenimi kötü', rightConcept: 'İlk izlenimi mükemmel' },
  { id: 'p142', leftConcept: 'Sonradan açılır', rightConcept: 'İlk saniyede etkiler' },
  { id: 'p143', leftConcept: 'Dizi karakteri', rightConcept: 'Gerçek insan' },
  { id: 'p144', leftConcept: 'Fanfiction malzemesi', rightConcept: 'Mahalle çocuğu' },
  { id: 'p145', leftConcept: 'TikTok editi', rightConcept: 'Vesikalık fotoğraf' },
  { id: 'p146', leftConcept: 'Pinterest', rightConcept: 'Facebook' },
  { id: 'p147', leftConcept: 'Chill', rightConcept: 'Kaotik' },
  { id: 'p148', leftConcept: 'Çay', rightConcept: 'Tekila' },
  { id: 'p149', leftConcept: 'Pamuk', rightConcept: 'Zımpara' },
  { id: 'p150', leftConcept: 'Kedi gibi', rightConcept: 'Kurt gibi' },
  { id: 'p151', leftConcept: 'Yavru köpek', rightConcept: 'Panter' },
  { id: 'p152', leftConcept: 'Melek yüzlü', rightConcept: 'Şeytan gülüşlü' },
  { id: 'p153', leftConcept: 'Evcil', rightConcept: 'Yabani' },
  { id: 'p154', leftConcept: 'Zararsız', rightConcept: 'Baş belası' },
  { id: 'p155', leftConcept: 'Düzgün insan', rightConcept: 'Yürüyen felaket' },
  { id: 'p156', leftConcept: 'Sakin bebito', rightConcept: 'Drama mıknatısı' },
  { id: 'p157', leftConcept: 'Sorunsuz', rightConcept: 'Problem makinesi' },
  { id: 'p158', leftConcept: 'Kaliteli', rightConcept: 'Tekinsiz' },
  { id: 'p159', leftConcept: 'Premium', rightConcept: 'TEMU' },
  { id: 'p160', leftConcept: 'Sade', rightConcept: 'Gösterişli' },
  { id: 'p161', leftConcept: 'Doğal', rightConcept: 'Yapay' },
  { id: 'p162', leftConcept: 'Mütevazı çekicilik', rightConcept: 'Gösterişli çekicilik' },
  { id: 'p163', leftConcept: 'Göz önünde', rightConcept: 'Gizli cevher' },
  { id: 'p164', leftConcept: 'İlk görüşte unutulur', rightConcept: 'İlk görüşte unutulmaz' },
  { id: 'p165', leftConcept: 'Flört potansiyeli düşük', rightConcept: 'Flört potansiyeli yüksek' },
  { id: 'p166', leftConcept: 'Magnet', rightConcept: 'İtici' },
  { id: 'p167', leftConcept: 'Elektrik verir', rightConcept: 'Elektrik keser' }
];

export const CARDS_PLUS = [...CARDS, ...PLUS_CARDS];

export function getRandomCard() {
  return CARDS[Math.floor(Math.random() * CARDS.length)];
}

// target from -85 to 85
export function getRandomTarget() {
  return Math.floor(Math.random() * 171) - 85; 
}
